@After.WebAPI_HostAddress = http://localhost:7200

### Send POST request to create an order
POST {{After.WebAPI_HostAddress}}/Order/
Content-Type: application/json

{
  "customerId": 123,
  "items": [
    {
      "itemId": 1,
      "quantity": 1
    },
    {
      "itemId": 2,
      "quantity": 2
    }
  ]
}

###
