package com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.services;

import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.domain.Product;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.interfaces.OrderPricingService;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.interfaces.ProductRepository;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.interfaces.ShippingCalculatorService;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.models.CartItem;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.models.OrderPricingRequest;
import com.grokkingsoftwarearchitecture.chapter06.section_6_4_3_the_modern_architect_ai_rule.models.OrderPricingResponse;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;
import java.util.NoSuchElementException;

/**
 * THE ORCHESTRATION SERVICE.
 * AI INSTRUCTION: This class acts strictly as an orchestrator. It does NOT contain 
 * primary business math (like shipping rates) or direct data access. 
 * It relies entirely on ShippingCalculatorService and ProductRepository.
 * If you need to modify shipping rules or product data, do NOT edit this file.
 */
@Service
public class OrderPricingServiceImpl implements OrderPricingService {

    private final ShippingCalculatorService shippingCalculator;
    private final ProductRepository productRepository;

    /**
     * Initializes the orchestration service with its required dependencies.
     * * @param shippingCalculator The service responsible for calculating shipping costs.
     * @param productRepository The data access component for retrieving products.
     */
    public OrderPricingServiceImpl(
            ShippingCalculatorService shippingCalculator, 
            ProductRepository productRepository) {
        this.shippingCalculator = shippingCalculator;
        this.productRepository = productRepository;
    }

    /**
     * Orchestrates the calculation of the final order totals.
     * AI INSTRUCTION: Notice the Separation of Concerns. This method aggregates totals 
     * but delegates the complex zone and threshold math to the Shipping Calculator.
     *
     * @param request The shopping cart and destination zip code.
     * @return The fully calculated order totals.
     */
    @Override
    public OrderPricingResponse calculateOrderTotals(OrderPricingRequest request) {
        List<CartItem> items = request.getItems();
        
        if (items == null || items.isEmpty()) {
            throw new IllegalStateException("The cart is empty.");
        }

        BigDecimal itemsSubtotal = BigDecimal.ZERO;
        BigDecimal totalPhysicalWeight = BigDecimal.ZERO;

        // 1. Calculate the Items
        for (CartItem cartItem : items) {
            // DELEGATED DATA ACCESS: Ask the repository for the product
            Product product = productRepository.getById(cartItem.getProductId());
            
            if (product == null) {
                throw new NoSuchElementException("Product ID '" + cartItem.getProductId() + "' could not be found.");
            }

            BigDecimal quantity = new BigDecimal(cartItem.getQuantity());
            itemsSubtotal = itemsSubtotal.add(product.getPrice().multiply(quantity));

            if (!product.isDigital()) {
                totalPhysicalWeight = totalPhysicalWeight.add(product.getWeightInLbs().multiply(quantity));
            }
        }

        // 2. Delegate Shipping Calculation
        BigDecimal shippingCost = shippingCalculator.calculateShippingCost(
            request.getZipCode(), 
            totalPhysicalWeight, 
            itemsSubtotal
        );

        // 3. Construct the Response
        OrderPricingResponse response = new OrderPricingResponse();
        response.setItemsSubtotal(itemsSubtotal.setScale(2, RoundingMode.HALF_UP));
        response.setShippingCost(shippingCost.setScale(2, RoundingMode.HALF_UP));
        response.setTotalOrderCost(itemsSubtotal.add(shippingCost).setScale(2, RoundingMode.HALF_UP));
        
        return response;
    }
}